### ISSUE TITLE
Prefigure as a service

### ISSUE THREAD

**Issue by StevenClontz** [davidaustinm/prefigure#2]
One bit of friction for adopting Prefigure is that it uses Python rather than Javascript. I don't think anyone is up for a port to Javascript, but maybe if we had a Prefigure server (similar to how WebWork servers function), we could have live web rendering of Prefigure to images.

Or alternatively, we might use e.g. https://wasmer.io/posts/py2wasm-a-python-to-wasm-compiler to make this library available to Javascript in the browser.

Just tossing the idea out somewhere.

**Comment by davidaustinm** [comment]
I think this is a good idea.  In fact, a group of us are actively planning to make PreFigure into a service, as you suggest.  I can fill you in some more in person.  I will note that some of the issues causing friction are likely to appear when/if the PreTeXt CLI supports a braille target.  

I'm not familiar with ps2wasm but will check it out.  Thanks for the reference.
