### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by oscarlevin** [davidaustinm/prefigure#3]
I think we had discussed lowering the prefigure python requirement to 3.8.5.  If not, we will need to raise the requirement for pretext to 3.10.  I'm working on adding support to the CLI, but can't test until I get the versions resolved.

**Comment by davidaustinm** [comment]
The python version of prefig has been lowered to python = "^3.8.5" which I believe is the same requirement as the pretext-cli.

**Comment by oscarlevin** [comment]
So it turns out this is more complicated.  To allow 3.8 python, we need numpy <= 1.24.  But then python 3.12 is not supported.  

I don't know if there is some way to specify requirements based on other requirements.  Or perhaps we just bump up to python 3.9+?

**Comment by davidaustinm** [comment]
I believe this is the problem I was running into earlier, but quite a bit of digging around showed me a way around it.  This is from the PreFigure pyproject.toml (you will likely see a similar problem with scipy):

python = "^3.8.5"
scipy = "^1.5" 
numpy = "^1.19"

I have set up a python3.12 virtual environment and installed a working version of PreFigure using these dependencies.  Can you confirm with "pip install prefig" in a 3.12 environment?

With that said, I would be more comfortable moving to python3.9+ now that 3.8 is at its end of life.  It won't make a difference for codespace users, and I would assume those users who install pretext locally would be savvy enough to upgrade fairly easy.  Given the relative size of the user bases though, I'm comfortable following your lead.
